---
title: "Presentaties"
subtitle: "none"
link: "https://werkgroep-toetsen-op-afstand.github.io/assessment-selection-tool/methods/presentation/"
date: '2021-12-08'
weight: 2
category: "tool"
---
Op kleine schaal kan kennis ook worden getoetst met een (groeps)presentatie. Hiermee kunnen, naast feitenkennis en begrip, ook presentatievaardigheden worden getoetst. De gelegenheid die een presentatie biedt voor interactie, bijvoorbeeld het stellen van vragen na afloop van de presentatie, biedt de beoordelaar extra mogelijkheden voor het toetsen van het begrip van de student. In het geval van een relatief kleine groep studenten kan gekozen worden voor individuele presentaties; het voordeel hiervan is dat dit een beter zicht kan geven op de mate waarin iedere afzonderlijke student de kennis beheerst. Het afnemen en beoordelen van presentaties kan echter veel tijd kosten. Door de studenten in groepen op te delen en per groep te laten presenteren kan de benodigde tijd worden beperkt. Maak bij de keuze tussen individuele presentaties of groepspresentaties een afweging tussen de wenselijkheid van een beter zicht op de prestaties van individuele studenten enerzijds en de praktische haalbaarheid anderzijds.