---
title: "Toetsvormen op afstand"
icon: /icons/tools.png
menuicon: /icons/tools-menu.png
date: 2020-07-31T11:05:44+02:00
expandable: false
instructions: false
weight: 3
---

## Digitale toets

Klik [hier](https://werkgroep-toetsen-op-afstand.github.io/assessment-selection-tool/methods/digital_assessment/) voor meer informatie over digitaal toetsen.  
<br>

**Tips voor deze toetsvorm**
```{r, child="../../snippets/knowledge/know_methods_mc.md"}
```

```{r, child="../../snippets/knowledge/know_methods_limitations.md"}
```

```{r, child="../../snippets/knowledge/know_methods_breakoutrooms.md"}
```

## Presentaties
Klik [hier]( https://werkgroep-toetsen-op-afstand.github.io/assessment-selection-tool/methods/presentation) voor meer informatie over presentaties.  
<br>

**Tips voor deze toetsvorm**
```{r, child="../../snippets/knowledge/know_methods_questions.md"}
```

```{r, child="../../snippets/knowledge/know_methods_video.md"}
```

```{r, child="../../snippets/knowledge/know_methods_groups-presentations.md"}
```

```{r, child="../../snippets/knowledge/know_methods_peerfeedback.md"}
```

```{r, child="../../snippets/knowledge/know_methods_ID.md"}
```

## Mondeling examen
Klik [hier]( https://werkgroep-toetsen-op-afstand.github.io/assessment-selection-tool/methods/oral_exam/) voor meer informatie over mondelinge examens.  
<br>

**Tips voor deze toetsvorm**
```{r, child="../../snippets/knowledge/know_methods_groups-oral.md"}
```

```{r, child="../../snippets/knowledge/know_methods_peerfeedback.md"}
```

```{r, child="../../snippets/knowledge/know_methods_ID.md"}
```
