---
title: "Presentaties"
subtitle: "none"
link: "https://werkgroep-toetsen-op-afstand.github.io/assessment-selection-tool/methods/presentation/"
date: '2021-12-08'
weight: 2
category: "tool"
---

Hogere cognitieve vaardigheden kunnen ook worden getoetst met een (groeps)presentatie. Een presentatie biedt studenten ruimte voor originaliteit en creativiteit. Daarnaast kunnen hiermee ook presentatievaardigheden worden getoetst. De gelegenheid die een presentatie biedt voor interactie, bijvoorbeeld het stellen van vragen na afloop van de presentatie, biedt de beoordelaar extra mogelijkheden voor het toetsen van het inzicht van de student. In het geval van een gemiddeld grote groep studenten dient het aanbeveling om, wanneer mogelijk, de studenten in groepen op te delen en ze per groep te laten presenteren, om de beoordelingstijd te beperken. 

Hoewel presentaties vaak op locatie plaatsvinden, zijn er ook mogelijkheden om dit op afstand te doen door gebruik te maken van videoconferencing software zoals Zoom of Microsoft Teams. Dit kan docenten en studenten reistijd en -kosten besparen. 