---
title: "Digitaal Toetsen"
subtitle: "none"
link: "https://werkgroep-toetsen-op-afstand.github.io/assessment-selection-tool/methods/digital_assessment/"
date: '2021-12-08'
weight: 1
category: "tool"
---

Met een digitale toets kunnen ook hogere cognitieve vaardigheden worden getoetst als toepassen, analyseren, synthetiseren en evalueren. Voor het op kleine schaal toetsen van hogere cognitieve vaardigheden zijn open vragen bij uitstek geschikt (Van Berkel, Bax, & Joosten-ten-Brinke, 2017). Open vragen bieden ruimte voor doelen waarbij originaliteit of creativiteit een rol spelen (Van Berkel, Bax, & Joosten-ten-Brinke, 2017). Bovendien is het bij ongeveer 50 of minder studenten efficiënter om gebruik te maken van open vragen dan van gesloten vragen; hoewel open vragen meer nakijktijd kosten, kost het minder tijd om ze te construeren, zeker bij het toetsen van hogere cognitieve vaardigheden (Van Berkel, 1999). Hoewel hogere cognitieve vaardigheden wel degelijk ook met gesloten vragen getoetst kunnen worden, vergt een zorgvuldige constructie hiervan tijd (Van Berkel, Bax, & Joosten-ten-Brinke, 2017). Een reden om toch te kiezen voor gesloten vragen is dat zij sneller te beantwoorden zijn door studenten, waardoor meer vragen kunnen worden opgenomen in de toets, wat de representativiteit ervan verhoogt (Van Berkel, 1999). 

Alternatieven voor een toets met open en/of gesloten vragen zijn open boek-tentamens of casustoetsen. Dit is op afstand minder fraudegevoelig dan het afnemen van toetsen met alleen gesloten vragen, maar wel arbeidsintensiever. Dit is daarom vooral een optie wanneer er genoeg mankracht beschikbaar is om dit te realiseren, bijvoorbeeld door junior docenten in te zetten. 

Op kleine schaal is het goed haalbaar om live proctoring toe te passen. Dit houdt in dat studenten in real-time, via bijvoorbeeld een webcam of telefoon, worden bekeken.   