---
title: "Aanpak"
icon: /icons/tools.png
menuicon: /icons/tools-menu.png
date: 2020-07-31T11:05:44+02:00
expandable: true
instructions: false
weight: 3
---

De online aanpak van de verschillende portfolio toepassingen verschillen nauwelijks van de reguliere aanpak.

## Vooraf

Uiteraard dienen de verschillende competenties helder geformuleerd en digitaal beschikbaar gesteld worden. De competenties kunnen in sommige gevallen al in de gespecialiseerde portfolio software worden opgenomen. 

## Tijdens

Gedurende het portfolio traject kunnen verschillende online bijeenkomsten worden opgezet. Hier valt te denken aan een online aftrap, applicatie uitleg of coaching.

## Na afloop 

Ter afronding kan ook het assessment gesprek online plaatsvinden. Dit kan in sommige gevallen gecombineerd worden met een online presentatie waarin de kandidaat de de verzamelde bewijsstukken in het portfolio toelicht.

## Aandachtspunten 

*	Zorg dat het portfolio, de toetsing en de onderwijsactiviteiten goed op elkaar zijn afgestemd. Studenten voelen zich dan verantwoordelijker voor hun portfolio. 
*	Voor studenten met een studiebeperking zoals add of adhd is het extra belangrijk duidelijk te communiceren over de verwachtingen en de inlevermomenten. Het is voor deze doelgroep raadzaam om met tussenproducten te werken om zo het werk overzichtelijk te houden. 
