---
title: "Tips"
icon: /icons/tips.png
menuicon: /icons/tips-menu.png
date: 2020-07-31T11:05:44+02:00
expandable: false
instructions: false
weight: 4
---

*	Faciliteer een stimuleer zelfsturend leren bij de totstandkoming van het portfolio. Laat studenten persoonlijke leerdoelen opstellen en hierop reflecteren. Vraag de student aan te geven op welk (deel)aspect ze in ieder geval graag feedback zouden willen krijgen. Je kunt er als beoordelaar natuurlijk voor kiezen ook op andere aspecten feedback te geven. 
*	Bied de mogelijkheid tot peerfeedback. Laat studenten bijvoorbeeld zelf vragen bedenken en stellen bij elkaars portfolio. Op deze manier bevorder je niet alleen dat studenten leren om op een constructieve manier kritisch te zijn en feedback te geven, maar krijgt de student ook zicht op vragen die er nog leven bij derden na het lezen van het portfolio. Zie [deze publicatie van Inholland voor meer informatie over het organiseren van peerfeedback](https://www.inholland.nl/media/18717/inh_factsheet-peerreview_a4-nl-digitaal.pdf).
*	Bespreek een portfolio eens formatief in een groepsassessment. Laat bijvoorbeeld één of twee (ouderejaars) medestudenten als mede-assessor optreden en geef de student die het portfolio heeft opgesteld de gelegenheid te reageren op de bruikbaarheid van de feedback. 
*	Geef de studenten de opdracht bij het portfolio ook een zelfbeoordeling in te leveren op basis van het beoordelingsformulier. Ze worden zo gedwongen te reflecteren op hun eigen prestaties. Als je hen daarbij vraagt aan te geven op welke plaats de informatie bij elk beoordelingscriterium vindbaar is, kan dat jou als beoordelaar tijd besparen tijdens het nakijken. 
