---
title: "Aanpak"
icon: /icons/tools.png
menuicon: /icons/tools-menu.png
date: 2020-07-31T11:05:44+02:00
expandable: true
instructions: false
weight: 3
---

## Voorbereiding 

De voorbereiding voor online projecten en producten verschilt nauwelijks van de voorbereiding bij campus onderwijs. Eerst inventariseer je welke leerdoelen behaald moeten worden door de student. Daarna ontwerp je een opdracht die ervoor zorgt dat deze leerdoelen getoond kunnen worden, bijvoorbeeld in de vorm van producten. Ook schets je de kaders waarbinnen het project of product moet worden afgerond. 

Het is belangrijk dat de kaders zoals de beoordelingscriteria/rubric, feedbackmomenten en de inleverdatum vooraf duidelijk zijn gecommuniceerd met de student. Het is verstandig om een aantal uitgewerkte voorbeeldprojecten of -producten te delen en te bespreken met de studenten. 

Sommige studenten vinden het lastig om te beginnen met een nieuw project en hebben last van uitstelgedrag. Je kunt deze studenten helpen door verschillende mijlpalen vast te stellen (bijvoorbeeld: in week 2 van het project is de introductie af). Je zet dit als docent nog meer kracht bij wanneer je de studenten beloont als zij zich aan de planning houden. Bijvoorbeeld door (peer)feedback momenten in te plannen als mijlpalen. 

Bied de studenten keuzeruimte binnen de kaders. Laat ze bijvoorbeeld zelf kiezen uit een selectie onderwerpen, geef ze ruimte in de vorm die hun product aanneemt en in de bronnen die ze raadplegen. Verder kun je overwegen om van de opdracht een groepsopdracht te maken. Bij groepsopdrachten hebben studenten meer interactie met elkaar en kunnen ze samen een project uitvoeren dat ze alleen nooit hadden kunnen realiseren.

## Tijdens

Bij online begeleiding van projecten is het voor de docent lastig om inzicht te krijgen in de voortgang van het project, product of het denkproces van de student. Bij groepsopdrachten mis je mogelijk belangrijke informatie over de samenwerking binnen de groep. Het is daarom van belang om tijdens de online begeleiding van een project op een aantal momenten beschikbaar te zijn voor de student (bijvoorbeeld tijdens Q&A sessies) en daarnaast de studenten actief op te zoeken. 

Studenten leren niet alleen van de docent, maar ook door samen in gesprek te gaan over het project of product. Als docent kun je dit faciliteren door bijvoorbeeld gebruik te maken van peerfeedbacktools waarmee studenten elkaar feedback kunnen geven. Zie [deze publicatie van Inholland voor meer informatie over het organiseren van peerfeedback](https://www.inholland.nl/media/18717/inh_factsheet-peerreview_a4-nl-digitaal.pdf). 


## Na afloop

Wat doen studenten met de feedback die je ze hebt gegeven tijdens de eindbeoordeling? Om ervoor te zorgen dat er daadwerkelijk wat met de feedback gedaan zal worden, kun je een reflectieopdracht overwegen. Laat student bijvoorbeeld kort reflecteren op de leerdoelen of op jouw feedback op hun project of product. Ook kun je de student bij latere projecten of producten de opdracht geven om de eerdere feedback nog eens te bekijken en te vragen hoe ze dit gaan meenemen in het nieuwe project of product.
