---
title: "Online"
icon: /icons/why-do-this.png
menuicon: /icons/why-do-this-menu.png
date: 2020-07-31T11:05:44+02:00
expandable: true
instructions: false
weight: 2
---

Observeren op afstand kan op drie manieren:

1. Live meekijken naar een online handeling. Het kan gaan om een online handeling (bijvoorbeeld het werken met een digitaal computerprogramma) of een handeling die (anders dan normaal) voor de beoordeling online plaatsvindt (bijvoorbeeld het voeren van een gesprek). De observatie is plaatsonafhankelijk.
2. Live meekijken naar een handeling op locatie. De beoordelaar(s) kijken vanaf afstand live mee (bijvoorbeeld bij het gebruik van een machine op een stageplek). De observatie is plaatsonafhankelijk. 
3. Bekijken van een video-opname. De student neemt de handeling op video op (bijvoorbeeld het geven van een les op de stage wordt opgenomen met daarvoor bestemde apparatuur).

## Voor- en nadelen

Het grootste voordeel van observeren op afstand is dat het plaats onafhankelijk kan, en bij een video-opname ook tijdsonafhankelijk. Dit maakt observeren voor een beoordelaar minder tijdrovend door het ontbreken van bijvoorbeeld reistijd. Ook het beoordelen door meerdere beoordelaars is gemakkelijker te organiseren. Uit onderzoek blijkt dat de validiteit van observaties vaak sterk toeneemt door het toevoegen van extra observaties of beoordelaars, iets wat het observeren op afstand vergemakkelijkt. 
Een ander voordeel van een video-opname is dat de beoordelaar samen met de student de video kan terug kijken om bijvoorbeeld een beoordeling te onderbouwen. De student kan de video ook terugkijken voor reflectie.

Bij observeren op afstand kan de informatie voor de beoordelaar beperkter zijn dan op locatie. Bijvoorbeeld bij het observeren van een les die door een student gegeven wordt op zijn stageschool in het primair onderwijs heeft de beoordelaar niet de mogelijkheid om een rondje langs de kinderen te lopen of kan het zicht via het beeld beperkt zijn als er bijvoorbeeld buiten beeld kinderen op de gang gaan werken. Ook kan het lastiger zijn om non-verbale communicatie goed te interpreteren. Als de informatie voor de beoordelaar te beperkt is, dan kan de validiteit van de beoordeling in het geding komen. De voor- en nadelen moeten daarom in iedere beoordelingscontext goed worden afgewogen.  

### Belangrijkste voordelen	

* Minder tijdrovend voor de beoordelaar
* Meerdere beoordelaars gemakkelijker te organiseren 
* Samen terug kijken met de student

### Belangrijkste nadeel

* Mogelijk beperktere informatie als beoordelaar

**Combineren** Een observatie kan worden uitgevoerd in combinatie met een assessmentgesprek om de student de gemaakte keuzes te laten motiveren. 
