---
title: "Toetsvormen op afstand"
icon: /icons/tools.png
menuicon: /icons/tools-menu.png
date: 2020-07-31T11:05:44+02:00
expandable: false
instructions: false
weight: 3
---

## Digitaal toetsen

Klik [hier](https://werkgroep-toetsen-op-afstand.github.io/assessment-selection-tool/methods/digital_assessment/) voor meer informatie over digitaal toetsen.  
<br>

Een voor de hand liggende vorm van een kennistoets is een multiple choice-toets of een toets met open vragen. Voor het toetsen van feitenkennis en/of begrip kan het beste (voornamelijk) gebruikgemaakt worden van gesloten vragen. Op dit cognitieve niveau zijn gesloten vragen relatief gemakkelijk te construeren. Het voordeel van gesloten vragen is dat deze sneller te beantwoorden zijn door studenten, waardoor meer vragen kunnen worden opgenomen in de toets, wat de representativiteit ervan verhoogt (Van Berkel, 1999). 

Op kleine schaal is het goed haalbaar om live proctoring toe te passen.  

# Mondeling 
Klik [hier](https://werkgroep-toetsen-op-afstand.github.io/assessment-selection-tool/methods/oral_exam/) voor meer informatie over mondelinge examens.  

Op kleine schaal kan kennis ook worden getoetst met een mondeling examen. Hiermee kunnen, naast feitenkennis en begrip, ook mondelinge vaardigheden worden getoetst. Een mondeling examen biedt de beoordelaar mogelijkheden om door te vragen op gegeven antwoorden, waarmee een betere inschatting kan worden gemaakt van het begrip van de student. In het geval van een relatief kleine groep studenten kan gekozen worden voor mondelinge examens met individuele studenten; het voordeel hiervan is dat dit een meer betrouwbare inschatting mogelijk maakt van de mate waarin een individuele student de kennis beheerst. Het beoordelen van mondelinge examens kan echter veel tijd kosten. Door de studenten in groepen op te delen en mondelinge groepsgesprekken te houden kan de beoordelingstijd worden beperkt. Maak bij de keuze tussen individuele gesprekken of groepsgesprekken een afweging tussen de wenselijkheid van een beter zicht op de prestaties van individuele studenten enerzijds en de praktische haalbaarheid anderzijds. 

## Presentaties
Klik [hier]( https://werkgroep-toetsen-op-afstand.github.io/assessment-selection-tool/methods/presentation) voor meer informatie over presentaties.  
<br>

Op kleine schaal kan kennis ook worden getoetst met een (groeps)presentatie. Hiermee kunnen, naast feitenkennis en begrip, ook presentatievaardigheden worden getoetst. De gelegenheid die een presentatie biedt voor interactie, bijvoorbeeld het stellen van vragen na afloop van de presentatie, biedt de beoordelaar extra mogelijkheden voor het toetsen van het begrip van de student. In het geval van een relatief kleine groep studenten kan gekozen worden voor individuele presentaties; het voordeel hiervan is dat dit een beter zicht kan geven op de mate waarin iedere afzonderlijke student de kennis beheerst. Het beoordelen van presentaties kan echter veel tijd kosten. Door de studenten in groepen op te delen en per groep te laten presenteren kan de beoordelingstijd worden beperkt. Maak bij de keuze tussen individuele presentaties of groepspresentaties een afweging tussen de wenselijkheid van een beter zicht op de prestaties van individuele studenten enerzijds en de praktische haalbaarheid anderzijds.