---
title: "Aanpak"
icon: /icons/tools.png
menuicon: /icons/tools-menu.png
date: 2020-07-31T11:05:44+02:00
expandable: true
instructions: false
weight: 3
---

## Voorbereiding

**Beoordelingsformulier** Houd er bij online afname rekening mee dat je het beoordelingsformulier misschien moet aanpassen omdat niet alle beoordelingscriteria op afstand te beoordelen zijn. Zo is behouden van de aandacht van het publiek online slecht te beoordelen.

**Anticiperen op technische problemen** Het organiseren van online presentaties verschilt iets van presentaties op locatie. Naast de 'reguliere' informatie (over planning, procedure, eventuele benodigdheden, verwachtingen, beoordeling) maak je ook afspraken over het werken in de online omgeving. Denk aan het delen van het scherm, het in- en uitschakelen van camera en microfoon, de wijze waarop vragen kunnen worden gesteld en de handelswijze bij technische problemen. Veel studenten vinden het een fijn idee als ze vooraf weten dat ze de presentatie opnieuw mogen doen als er technische problemen optreden. Ook kun je stimuleren dat studenten hun presentatie vooraf bij elkaar oefenen. Bij sommige instellingen kan de student apparatuur lenen of kun je een fysieke locatie aanbieden. Zorg er in ieder geval voor dat je tijdig en helder communiceert over de afspraken. 

**Opname** Een oplossing om de betrouwbaarheid van de beoordeling te vergroten is het opnemen van de presentatie tijdens de uitvoering. Bij twijfel over de beoordeling kan deze dan teruggekeken worden. Informeer de student vooraf over een eventuele opname. Het verwerken, opslaan en verwijderen van opnames moet plaatsvinden binnen de wettelijke kaders. Informeer bij je instelling wat hiervoor de regels zijn. 

**Meerdere beoordelaars** Om de betrouwbaarheid van de beoordeling nog meer te vergroten kunnen meerdere beoordelaars ingezet worden bij een online presentatie. Bij formatieve toetsen kunnen hiervoor medestudenten ingezet worden. Beoordelaars zouden de video opname ook achteraf kunnen beoordelen.

## Tijdens   

### Vlak voor de presentatie

*	Zorg voor opgeladen apparatuur.  
*	Zorg voor een rustige omgeving waarin je niet gestoord wordt.   
*	Test de apparatuur voorafgaand aan de toets, gebruik zo nodig een headset. 
*	Zorg dat je de benodigde documenten (rubric, beoordelingsformulier e.d.) geprint of op een tweede scherm bij de hand hebt.  
*	Log enkele minuten voorafgaand aan de toets in op de video vergadering.  

### Start

*	Stel de student gerust.  
*	Controleer of de regels en afspraken duidelijk zijn en herhaal ze zo nodig. 
*	Geef aan wanneer de student de beoordeling en/of feedback kan verwachten.  
*	Geef zo nodig aan dat er een opname wordt gemaakt. 

### Afname

*	Speel zo nodig in op technische problemen.

### Afsluiting

*	Als je met meerdere beoordelaars werkt en direct feedback wil geven, kun je de student vragen om even de videovergadering te verlaten of ze in een breakout room te zetten. Na het bespreken van de bevindingen kan je de student weer terug laten komen.

## Na afloop

Geef direct na de presentatie en (ruim) voor het delen van het cijfer feedback. Dit is het moment waarop feedback het best wordt geïnternaliseerd. Er kan bij een opname overwogen worden om deze na afloop aan de student beschikbaar te stellen.

## Aandachtspunten

*	Studenten vinden (online) presentaties vaak spannend. Duidelijkheid over wat ze kunnen verwachten helpt. Informeer de studenten daarom tijdig en volledig over inhoud, procedures, deelnemende beoordelaars en de wijze van beoordeling en maak afspraken over het werken in de online omgeving. Zeker voor studenten met een studiebeperking zoals autisme is dit belangrijk. Vraag aan deze studenten wat je kunt doen om het gesprek gemakkelijker te laten verlopen. 
