---
title: "Tips"
icon: /icons/tips.png
menuicon: /icons/tips-menu.png
date: 2020-07-31T11:05:44+02:00
expandable: false
instructions: false
weight: 4
---

*	Voer een assessmentgesprek in groepjes uit. Studenten bekijken vooraf elkaars producten, stellen vragen en geven peerfeedback. Uiteraard kan een examinator ook vragen stellen en feedback geven. Zie [deze publicatie van Inholland voor meer informatie over het organiseren van peerfeedback](https://www.inholland.nl/media/18717/inh_factsheet-peerreview_a4-nl-digitaal.pdf).
*	Faciliteer het oefenen van een assessmentgesprek door het inroosteren van een online bijeenkomst waarin studenten onderling kunnen oefenen. Zorg ervoor dat het beoordelingsformulier beschikbaar is een laat studenten elkaar feedback geven aan de hand van het beoordelingsformulier. Door het geven van peerfeedback leren studenten ook veel over de eigen prestatie, het stimuleert hun zelfbeoordelingsvermogen en ze doen inspiratie bij elkaar op. Zie [deze publicatie van Inholland voor meer informatie over het organiseren van peerfeedback](https://www.inholland.nl/media/18717/inh_factsheet-peerreview_a4-nl-digitaal.pdf). 
*	Door voorafgaand aan een online mondelinge toets een aantal representatieve oefenopgaven te delen is het voor de studenten duidelijker wat voor soort toetsvragen ze kunnen verwachten. Ze kunnen de oefenopgaven gebruiken om te evalueren of ze de studiestof voldoende beheersen. 
*	Stimuleer studenten om zelf ook toetsvragen te maken ter voorbereiding op een online mondeling. Met behulp van online flashcards kunnen de toetsvragen gedeeld worden als oefenmateriaal. Je kunt een deel van deze vragen ook gebruiken in de toets zelf. 
*	Geef direct na afloop van het assessmentgesprek en (ruim) voor het delen van het cijfer feedback aan de student. Dit is het moment waarop feedback het best geïnternaliseerd wordt. 
*	Voor een student kan een online assessmentgesprek als afronding van een scriptieproces of een afstudeerstage onpersoonlijk overkomen. Het doet niet altijd recht aan de inspanning die geleverd is. Bij dit soort gelegenheden heeft een gesprek op locatie duidelijk de voorkeur boven een online assessmentgesprek. 
*	Een mogelijk alternatief voor een online mondeling is een verwerkingsopdracht. 
*	Een mogelijk alternatief voor een online mondeling is een toets met open en/of gesloten vragen. 
*	Kijk of je kunt bijdragen aan een feedbackcultuur, bijvoorbeeld door een deel van de toetsen een formatieve in plaats van een summatieve functie te geven. Lees hier meer over in het boek Toetsrevolutie. 


```{r, child="../../../snippets/knowledge/know_methods_ID.md"} 
```
