---
title: "Definitie"
icon: /icons/what-to-do.png
menuicon: /icons/what-to-do-menu.png
date: 2020-07-31T11:05:44+02:00
expandable: false
instructions: false
weight: 1
---

Met projecten en producten past de student kennis toe op een actieve, praktische wijze binnen de gestelde kaders. Het toepassen van kennis leidt tot betere verwerking van de lesstof. Projecten en producten zijn geschikt om vast te stellen of de student kennis kan toepassen, analyseren, evalueren of creëren. 

Projecten en producten zijn minder geschikt om te beoordelen of iemand beschikt over een brede kennisbasis. In de praktijk worden projecten en producten dan ook vaak gecombineerd met toetsvormen die hiervoor wel geschikt zijn, zoals toetsen met open en/of gesloten vragen. Soms is het niet nodig om de kennisbasis apart te beoordelen, omdat deze bijvoorbeeld al eerder is beoordeeld bij een ander voorgaand vak of omdat deze in voldoende mate aan bod komt in het project/product. 

Een project of product wordt ook wel gecombineerd met een mondelinge toets of een presentatie. 
